openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Auto Scaling #Action=AttachInstances #Action=AttachInstances #Action=RollbackInstanceRefresh API'
  description: <fullname>Amazon EC2 Auto Scaling</fullname> <p>Amazon EC2 Auto Scaling is designed to automatically launch and terminate EC2 instances based on user-defined scaling policies, scheduled actions, and health checks.</p> <p>For more information, see the <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/">Amazon EC2 Auto Scaling User Guide</a> and the <a href="https://docs.aws.amazon.com/autoscaling/ec2/APIReference/Welcome.html">Amazon EC2 Auto Scaling API Reference</a>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: autoscaling
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/autoscaling-2011-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: https://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: http://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: https://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: http://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
- url: https://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=RollbackInstanceRefresh'
paths:
  /#Action=RollbackInstanceRefresh:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: RollbackInstanceRefresh
      operationId: GET_RollbackInstanceRefresh
      description: '<p>Cancels an instance refresh that is in progress and rolls back any changes that it made. Amazon EC2 Auto Scaling replaces any instances that were replaced during the instance refresh. This restores your Auto Scaling group to the configuration that it was using before the start of the instance refresh. </p> <p>This operation is part of the <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html">instance refresh feature</a> in Amazon EC2 Auto Scaling, which helps you update instances in your Auto Scaling group after you make configuration changes.</p> <p>A rollback is not supported in the following situations: </p> <ul> <li> <p>There is no desired configuration specified for the instance refresh.</p> </li> <li> <p>The Auto Scaling group has a launch template that uses an Amazon Web Services Systems Manager parameter instead of an AMI ID for the <code>ImageId</code> property.</p> </li> <li> <p>The Auto Scaling group uses the launch template''s <code>$Latest</code> or <code>$Default</code> version.</p> </li> </ul> <p>When you receive a successful response from this operation, Amazon EC2 Auto Scaling immediately begins replacing instances. You can check the status of this operation through the <a>DescribeInstanceRefreshes</a> API operation. </p>'
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/RollbackInstanceRefreshAnswer'
              examples:
                GET_RollbackInstanceRefresh200Example:
                  summary: Default GET_RollbackInstanceRefresh 200 response
                  x-microcks-default: true
                  value:
                    InstanceRefreshId: example-id-1234
        '480':
          description: LimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/LimitExceededFault'
              examples:
                GET_RollbackInstanceRefresh480Example:
                  summary: Default GET_RollbackInstanceRefresh 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                GET_RollbackInstanceRefresh481Example:
                  summary: Default GET_RollbackInstanceRefresh 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ActiveInstanceRefreshNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ActiveInstanceRefreshNotFoundFault'
        '483':
          description: IrreversibleInstanceRefreshFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/IrreversibleInstanceRefreshFault'
      parameters:
      - name: AutoScalingGroupName
        in: query
        required: false
        description: The name of the Auto Scaling group.
        schema:
          type: string
          minLength: 1
          maxLength: 255
          x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RollbackInstanceRefresh
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling GET_ Rollback Instance Refresh
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RollbackInstanceRefresh'
    post:
      x-aws-operation-name: RollbackInstanceRefresh
      operationId: POST_RollbackInstanceRefresh
      description: '<p>Cancels an instance refresh that is in progress and rolls back any changes that it made. Amazon EC2 Auto Scaling replaces any instances that were replaced during the instance refresh. This restores your Auto Scaling group to the configuration that it was using before the start of the instance refresh. </p> <p>This operation is part of the <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html">instance refresh feature</a> in Amazon EC2 Auto Scaling, which helps you update instances in your Auto Scaling group after you make configuration changes.</p> <p>A rollback is not supported in the following situations: </p> <ul> <li> <p>There is no desired configuration specified for the instance refresh.</p> </li> <li> <p>The Auto Scaling group has a launch template that uses an Amazon Web Services Systems Manager parameter instead of an AMI ID for the <code>ImageId</code> property.</p> </li> <li> <p>The Auto Scaling group uses the launch template''s <code>$Latest</code> or <code>$Default</code> version.</p> </li> </ul> <p>When you receive a successful response from this operation, Amazon EC2 Auto Scaling immediately begins replacing instances. You can check the status of this operation through the <a>DescribeInstanceRefreshes</a> API operation. </p>'
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/RollbackInstanceRefreshAnswer'
              examples:
                POST_RollbackInstanceRefresh200Example:
                  summary: Default POST_RollbackInstanceRefresh 200 response
                  x-microcks-default: true
                  value:
                    InstanceRefreshId: example-id-1234
        '480':
          description: LimitExceededFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/LimitExceededFault'
              examples:
                POST_RollbackInstanceRefresh480Example:
                  summary: Default POST_RollbackInstanceRefresh 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                POST_RollbackInstanceRefresh481Example:
                  summary: Default POST_RollbackInstanceRefresh 481 response
                  x-microcks-default: true
                  value: {}
        '482':
          description: ActiveInstanceRefreshNotFoundFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ActiveInstanceRefreshNotFoundFault'
        '483':
          description: IrreversibleInstanceRefreshFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/IrreversibleInstanceRefreshFault'
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/RollbackInstanceRefreshType'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - RollbackInstanceRefresh
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling POST_ Rollback Instance Refresh
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=RollbackInstanceRefresh'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    XmlStringMaxLen255:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    IrreversibleInstanceRefreshFault: {}
    ActiveInstanceRefreshNotFoundFault: {}
    LimitExceededFault: {}
    RollbackInstanceRefreshType:
      type: object
      title: RollbackInstanceRefreshType
      properties:
        AutoScalingGroupName:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen255'
          - description: The name of the Auto Scaling group.
    ResourceContentionFault: {}
    RollbackInstanceRefreshAnswer:
      type: object
      properties:
        InstanceRefreshId:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen255'
          - description: The instance refresh ID associated with the request. This is the unique ID assigned to the instance refresh when it was started.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/autoscaling/
x-hasEquivalentPaths: true
