openapi: 3.2.0
info:
  version: 1.0.0
  x-release: v4
  title: 'Auto Scaling #Action=AttachInstances #Action=AttachInstances #Action=DeleteLaunchConfiguration #Action=Delete Launch Configuration #Action=Delete Launch Configuration API'
  description: <fullname>Amazon EC2 Auto Scaling</fullname> <p>Amazon EC2 Auto Scaling is designed to automatically launch and terminate EC2 instances based on user-defined scaling policies, scheduled actions, and health checks.</p> <p>For more information, see the <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/">Amazon EC2 Auto Scaling User Guide</a> and the <a href="https://docs.aws.amazon.com/autoscaling/ec2/APIReference/Welcome.html">Amazon EC2 Auto Scaling API Reference</a>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: autoscaling
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/autoscaling-2011-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: https://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: http://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: https://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: http://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
- url: https://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=DeleteLaunchConfiguration'
paths:
  /#Action=DeleteLaunchConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: DeleteLaunchConfiguration
      operationId: GET_DeleteLaunchConfiguration
      description: <p>Deletes the specified launch configuration.</p> <p>The launch configuration must not be attached to an Auto Scaling group. When this call completes, the launch configuration is no longer available for use.</p>
      responses:
        '200':
          description: Success
        '480':
          description: ResourceInUseFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceInUseFault'
              examples:
                GET_DeleteLaunchConfiguration480Example:
                  summary: Default GET_DeleteLaunchConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                GET_DeleteLaunchConfiguration481Example:
                  summary: Default GET_DeleteLaunchConfiguration 481 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: LaunchConfigurationName
        in: query
        required: true
        description: The name of the launch configuration.
        schema:
          type: string
          minLength: 1
          maxLength: 255
          x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DeleteLaunchConfiguration
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling GET_ Delete Launch Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DeleteLaunchConfiguration'
    post:
      x-aws-operation-name: DeleteLaunchConfiguration
      operationId: POST_DeleteLaunchConfiguration
      description: <p>Deletes the specified launch configuration.</p> <p>The launch configuration must not be attached to an Auto Scaling group. When this call completes, the launch configuration is no longer available for use.</p>
      responses:
        '200':
          description: Success
        '480':
          description: ResourceInUseFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceInUseFault'
              examples:
                POST_DeleteLaunchConfiguration480Example:
                  summary: Default POST_DeleteLaunchConfiguration 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                POST_DeleteLaunchConfiguration481Example:
                  summary: Default POST_DeleteLaunchConfiguration 481 response
                  x-microcks-default: true
                  value: {}
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/LaunchConfigurationNameType'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - DeleteLaunchConfiguration
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling POST_ Delete Launch Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=DeleteLaunchConfiguration'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    ResourceInUseFault: {}
    LaunchConfigurationNameType:
      type: object
      required:
      - LaunchConfigurationName
      title: LaunchConfigurationNameType
      properties:
        LaunchConfigurationName:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen255'
          - description: The name of the launch configuration.
    XmlStringMaxLen255:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    ResourceContentionFault: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/autoscaling/
x-hasEquivalentPaths: true
