openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Auto Scaling #Action=AttachInstances #Action=AttachInstances #Action=TerminateInstanceInAutoScalingGroup API'
  description: <fullname>Amazon EC2 Auto Scaling</fullname> <p>Amazon EC2 Auto Scaling is designed to automatically launch and terminate EC2 instances based on user-defined scaling policies, scheduled actions, and health checks.</p> <p>For more information, see the <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/">Amazon EC2 Auto Scaling User Guide</a> and the <a href="https://docs.aws.amazon.com/autoscaling/ec2/APIReference/Welcome.html">Amazon EC2 Auto Scaling API Reference</a>.</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: autoscaling
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/autoscaling-2011-01-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: https://autoscaling.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Auto Scaling multi-region endpoint
- url: http://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: https://autoscaling.amazonaws.com
  variables: {}
  description: The general Auto Scaling endpoint for US East (N. Virginia)
- url: http://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
- url: https://autoscaling.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Auto Scaling endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#Action=TerminateInstanceInAutoScalingGroup'
paths:
  /#Action=TerminateInstanceInAutoScalingGroup:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      x-aws-operation-name: TerminateInstanceInAutoScalingGroup
      operationId: GET_TerminateInstanceInAutoScalingGroup
      description: <p>Terminates the specified instance and optionally adjusts the desired group size. This operation cannot be called on instances in a warm pool.</p> <p>This call simply makes a termination request. The instance is not terminated immediately. When an instance is terminated, the instance status changes to <code>terminated</code>. You can't connect to or start an instance after you've terminated it.</p> <p>If you do not specify the option to decrement the desired capacity, Amazon EC2 Auto Scaling launches instances to replace the ones that are terminated. </p> <p>By default, Amazon EC2 Auto Scaling balances instances across all Availability Zones. If you decrement the desired capacity, your Auto Scaling group can become unbalanced between Availability Zones. Amazon EC2 Auto Scaling tries to rebalance the group, and rebalancing might terminate instances in other zones. For more information, see <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html#AutoScalingBehavior.InstanceUsage">Rebalancing activities</a> in the <i>Amazon EC2 Auto Scaling User Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ActivityType'
              examples:
                GET_TerminateInstanceInAutoScalingGroup200Example:
                  summary: Default GET_TerminateInstanceInAutoScalingGroup 200 response
                  x-microcks-default: true
                  value:
                    Activity: example-string
        '480':
          description: ScalingActivityInProgressFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ScalingActivityInProgressFault'
              examples:
                GET_TerminateInstanceInAutoScalingGroup480Example:
                  summary: Default GET_TerminateInstanceInAutoScalingGroup 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                GET_TerminateInstanceInAutoScalingGroup481Example:
                  summary: Default GET_TerminateInstanceInAutoScalingGroup 481 response
                  x-microcks-default: true
                  value: {}
      parameters:
      - name: InstanceId
        in: query
        required: true
        description: The ID of the instance.
        schema:
          type: string
          minLength: 1
          maxLength: 19
          x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
      - name: ShouldDecrementDesiredCapacity
        in: query
        required: true
        description: Indicates whether terminating the instance also decrements the size of the Auto Scaling group.
        schema:
          type: boolean
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - TerminateInstanceInAutoScalingGroup
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling GET_ Terminate Instance in Auto Scaling Group
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=TerminateInstanceInAutoScalingGroup'
    post:
      x-aws-operation-name: TerminateInstanceInAutoScalingGroup
      operationId: POST_TerminateInstanceInAutoScalingGroup
      description: <p>Terminates the specified instance and optionally adjusts the desired group size. This operation cannot be called on instances in a warm pool.</p> <p>This call simply makes a termination request. The instance is not terminated immediately. When an instance is terminated, the instance status changes to <code>terminated</code>. You can't connect to or start an instance after you've terminated it.</p> <p>If you do not specify the option to decrement the desired capacity, Amazon EC2 Auto Scaling launches instances to replace the ones that are terminated. </p> <p>By default, Amazon EC2 Auto Scaling balances instances across all Availability Zones. If you decrement the desired capacity, your Auto Scaling group can become unbalanced between Availability Zones. Amazon EC2 Auto Scaling tries to rebalance the group, and rebalancing might terminate instances in other zones. For more information, see <a href="https://docs.aws.amazon.com/autoscaling/ec2/userguide/auto-scaling-benefits.html#AutoScalingBehavior.InstanceUsage">Rebalancing activities</a> in the <i>Amazon EC2 Auto Scaling User Guide</i>.</p>
      responses:
        '200':
          description: Success
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ActivityType'
              examples:
                POST_TerminateInstanceInAutoScalingGroup200Example:
                  summary: Default POST_TerminateInstanceInAutoScalingGroup 200 response
                  x-microcks-default: true
                  value:
                    Activity: example-string
        '480':
          description: ScalingActivityInProgressFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ScalingActivityInProgressFault'
              examples:
                POST_TerminateInstanceInAutoScalingGroup480Example:
                  summary: Default POST_TerminateInstanceInAutoScalingGroup 480 response
                  x-microcks-default: true
                  value: {}
        '481':
          description: ResourceContentionFault
          content:
            text/xml:
              schema:
                $ref: '#/components/schemas/ResourceContentionFault'
              examples:
                POST_TerminateInstanceInAutoScalingGroup481Example:
                  summary: Default POST_TerminateInstanceInAutoScalingGroup 481 response
                  x-microcks-default: true
                  value: {}
      requestBody:
        content:
          text/xml:
            schema:
              $ref: '#/components/schemas/TerminateInstanceInAutoScalingGroupType'
      parameters:
      - name: Action
        in: query
        required: true
        schema:
          type: string
          enum:
          - TerminateInstanceInAutoScalingGroup
      - name: Version
        in: query
        required: true
        schema:
          type: string
          enum:
          - 2011-01-01
      summary: Amazon EC2 Auto Scaling POST_ Terminate Instance in Auto Scaling Group
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#Action=TerminateInstanceInAutoScalingGroup'
components:
  schemas:
    XmlString:
      type: string
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    Progress:
      type: integer
    ActivityType:
      type: object
      properties:
        Activity:
          allOf:
          - $ref: '#/components/schemas/Activity'
          - description: A scaling activity.
    ResourceContentionFault: {}
    XmlStringMaxLen1023:
      type: string
      minLength: 1
      maxLength: 1023
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    ScalingActivityStatusCode:
      type: string
      enum:
      - PendingSpotBidPlacement
      - WaitingForSpotInstanceRequestId
      - WaitingForSpotInstanceId
      - WaitingForInstanceId
      - PreInService
      - InProgress
      - WaitingForELBConnectionDraining
      - MidLifecycleAction
      - WaitingForInstanceWarmup
      - Successful
      - Failed
      - Cancelled
      - WaitingForConnectionDraining
    ShouldDecrementDesiredCapacity:
      type: boolean
    TimestampType:
      type: string
      format: date-time
    TerminateInstanceInAutoScalingGroupType:
      type: object
      required:
      - InstanceId
      - ShouldDecrementDesiredCapacity
      title: TerminateInstanceInAutoScalingGroupType
      properties:
        InstanceId:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen19'
          - description: The ID of the instance.
        ShouldDecrementDesiredCapacity:
          allOf:
          - $ref: '#/components/schemas/ShouldDecrementDesiredCapacity'
          - description: Indicates whether terminating the instance also decrements the size of the Auto Scaling group.
    AutoScalingGroupState:
      type: string
      minLength: 1
      maxLength: 32
    XmlStringMaxLen19:
      type: string
      minLength: 1
      maxLength: 19
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    XmlStringMaxLen255:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    ScalingActivityInProgressFault: {}
    Activity:
      type: object
      required:
      - ActivityId
      - AutoScalingGroupName
      - Cause
      - StartTime
      - StatusCode
      properties:
        ActivityId:
          allOf:
          - $ref: '#/components/schemas/XmlString'
          - description: The ID of the activity.
        AutoScalingGroupName:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen255'
          - description: The name of the Auto Scaling group.
        Description:
          allOf:
          - $ref: '#/components/schemas/XmlString'
          - description: A friendly, more verbose description of the activity.
        Cause:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen1023'
          - description: The reason the activity began.
        StartTime:
          allOf:
          - $ref: '#/components/schemas/TimestampType'
          - description: The start time of the activity.
        EndTime:
          allOf:
          - $ref: '#/components/schemas/TimestampType'
          - description: The end time of the activity.
        StatusCode:
          allOf:
          - $ref: '#/components/schemas/ScalingActivityStatusCode'
          - description: The current status of the activity.
        StatusMessage:
          allOf:
          - $ref: '#/components/schemas/XmlStringMaxLen255'
          - description: A friendly, more verbose description of the activity status.
        Progress:
          allOf:
          - $ref: '#/components/schemas/Progress'
          - description: A value between 0 and 100 that indicates the progress of the activity.
        Details:
          allOf:
          - $ref: '#/components/schemas/XmlString'
          - description: The details about the activity.
        AutoScalingGroupState:
          allOf:
          - $ref: '#/components/schemas/AutoScalingGroupState'
          - description: The state of the Auto Scaling group, which is either <code>InService</code> or <code>Deleted</code>.
        AutoScalingGroupARN:
          allOf:
          - $ref: '#/components/schemas/ResourceName'
          - description: The Amazon Resource Name (ARN) of the Auto Scaling group.
      description: Describes scaling activity, which is a long-running process that represents a change to your Auto Scaling group, such as changing its size or replacing an instance.
    ResourceName:
      type: string
      minLength: 1
      maxLength: 1600
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/autoscaling/
x-hasEquivalentPaths: true
